CREATE TABLE locations (id VARCHAR(40) PRIMARY KEY, name VARCHAR(80), kind VARCHAR(30));
CREATE TABLE products (id VARCHAR(40) PRIMARY KEY, name VARCHAR(80));
CREATE TABLE inventory (location_id VARCHAR(40), product_id VARCHAR(40), stock INT NOT NULL, target INT, PRIMARY KEY(location_id,product_id), FOREIGN KEY(location_id) REFERENCES locations(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE replenishment_requests (id VARCHAR(36) PRIMARY KEY, destination VARCHAR(40) NOT NULL, origin VARCHAR(40) NOT NULL, status VARCHAR(25) NOT NULL, created_by VARCHAR(40), confirmed_by VARCHAR(40), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, confirmed_at TIMESTAMP NULL, FOREIGN KEY(destination) REFERENCES locations(id), FOREIGN KEY(origin) REFERENCES locations(id));
CREATE TABLE request_items (request_id VARCHAR(36), product_id VARCHAR(40), requested INT NOT NULL, received INT, PRIMARY KEY(request_id,product_id), FOREIGN KEY(request_id) REFERENCES replenishment_requests(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE documents (request_id VARCHAR(36) PRIMARY KEY, document_key VARCHAR(80) UNIQUE NOT NULL, status VARCHAR(40), protocol VARCHAR(80), reason VARCHAR(255), object_key VARCHAR(100), attempts INT NOT NULL DEFAULT 0, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(request_id) REFERENCES replenishment_requests(id));
INSERT INTO locations VALUES ('centro-horizonte','Centro Horizonte','CENTER'),('loja-aurora','Loja Aurora','STORE'),('loja-lagoa','Loja Lagoa','STORE');
INSERT INTO products VALUES ('agua-500','Água 500 ml'),('cafe-250','Café 250 g'),('arroz-1000','Arroz 1 kg');
INSERT INTO inventory VALUES ('centro-horizonte','agua-500',100,NULL),('centro-horizonte','cafe-250',50,NULL),('centro-horizonte','arroz-1000',40,NULL),('loja-aurora','agua-500',4,10),('loja-aurora','cafe-250',3,5),('loja-aurora','arroz-1000',10,10),('loja-lagoa','agua-500',2,8),('loja-lagoa','cafe-250',7,5),('loja-lagoa','arroz-1000',1,6);
