server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 valid=5s ipv6=off;
    location /admin/ {
        set $core_upstream core:8080;
        proxy_pass http://$core_upstream$request_uri;
        proxy_read_timeout 30s;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
